jenkins:
  image: jenkins
  ports:
    - "50000:50000"
    - "8080:8080"
  volumes:
    - /Users/Modulus/jenkins_builds/:/var/jenkins_home
nexus:
  image: sonatype/nexus
  ports:
    - "8081:8081"
gocd:
  image: gocd/gocd-dev
  ports:
    - "8153:8153"
    - "8154:8154"
